version: "3"
services:
  db:
    container_name: my-mysql
    image: ihcomegag.jfrog.io/handson-docker/my-mysql-image:1.0
    expose:
      - 3306
  app:
    container_name: sample-application-container
    image: ihcomegag.jfrog.io/handson-docker/sample-application:0.0.1
    depends_on:
      - db
    ports:
      - "8888:8080"
    volumes:
      - "./app4handson/build/libs:/work"
    entrypoint: "java -jar /work/app4handson-0.0.1.jar"